/*
 * Seed: Star Leap Gesture Platformer
 *
 * Real per-session lesson content (no roadmap). 8 one-hour sessions. Each
 * session ends with a runnable mini-game state, plus a "Try this" tryout.
 *
 * Run with:   node backend/scripts/seedHandGesturePlatformerProject.js
 */

const pool = require('../src/config/db');
const {
  createLearningTables,
  createLearningProject,
  replaceLearningContentChunks,
} = require('../src/models/learningModel');

const PROJECT_TITLE = 'Star Leap Gesture Platformer';
const FALLBACK_CLASS_NAME = 'JHS 3';
const SECTION_COUNT = 8;

const chunks = [
  {
    title: 'Before we start: what you need on the laptop',
    source_type: 'setup',
    audience: 'both',
    tags: ['setup', 'pygame', 'install'],
    content: [
      'Biggest project of the gesture set. Python 3.11 or 3.12 (not 3.14). In Terminal:',
      '',
      '    cd hand_gesture_platformer',
      '    python3.11 -m venv .venv',
      '    source .venv/bin/activate',
      '    pip install opencv-python mediapipe numpy pygame',
      '',
      'pygame is what draws the game world (sky, ground, player, enemies). OpenCV + MediaPipe still read the camera in the background and turn your hand into game inputs. Make one file gesture_platformer.py — every session adds to it. Run with python gesture_platformer.py.',
      '',
      'IMPORTANT: this game uses BOTH the keyboard AND the camera. We add the camera in Session 4 — until then we play with the arrow keys so kids see progress every class even if a camera fails.',
    ].join('\n'),
  },

  // S1
  {
    step_number: 1,
    title: 'Section 1: Today a pygame window opens with sky, ground, and a player',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-1', 'pygame', 'window'],
    content: [
      'TODAY: Open a 960×540 pygame window. Sky gradient at the top, brown ground at the bottom, a cyan rectangle as the player standing on the ground.',
      '',
      'WHY: pygame works differently from OpenCV — it has a fixed window, a game clock, and a frame-by-frame loop. We learn the skeleton first.',
      '',
      'TYPE THIS into gesture_platformer.py:',
      '',
      '    import pygame, sys',
      '    pygame.init()',
      '    screen = pygame.display.set_mode((960, 540))',
      '    pygame.display.set_caption("Star Leap")',
      '    clock = pygame.time.Clock()',
      '    player = pygame.Rect(80, 478 - 54, 38, 54)',
      '    while True:',
      '        for event in pygame.event.get():',
      '            if event.type == pygame.QUIT: pygame.quit(); sys.exit()',
      '        # sky gradient',
      '        for y in range(540):',
      '            t = y / 540',
      '            color = (int(18*(1-t)+62*t), int(24*(1-t)+72*t), int(48*(1-t)+108*t))',
      '            pygame.draw.line(screen, color, (0, y), (960, y))',
      '        pygame.draw.rect(screen, (88, 56, 42), (0, 478, 960, 80))   # dirt',
      '        pygame.draw.rect(screen, (78, 210, 105), (0, 478, 960, 6))  # grass strip',
      '        pygame.draw.rect(screen, (80, 245, 255), player)',
      '        pygame.display.flip()',
      '        clock.tick(60)',
      '',
      'RUN IT. A window with a blue sky and a small cyan square sitting on the green grass. Close it with the window X.',
      '',
      'WHAT IS GOING ON: pygame.Rect(x, y, w, h) is a rectangle — the player. pygame.draw.rect paints it. clock.tick(60) caps the game at 60 frames per second. The sky gradient is just 540 horizontal lines, each blending between two colours.',
      '',
      'TRY THIS: Move the player by changing pygame.Rect(80, 478-54, ...) — try 200 or 400. Then change the player\'s colour from cyan to pink. Then change the grass colour to red — a Mars planet!',
    ].join('\n'),
  },

  // S2
  {
    step_number: 2,
    title: 'Section 2: Today arrow keys move the player, and gravity pulls them down',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-2', 'physics', 'gravity'],
    content: [
      'TODAY: Press LEFT / RIGHT to move. Player falls with gravity until they hit the ground. This is the basic physics every Mario game uses.',
      '',
      'WHY: Two variables — vx (horizontal speed) and vy (vertical speed). Every frame: vy gets bigger (gravity), position changes by speed, then we check "did I hit the ground?". That is the whole secret.',
      '',
      'REPLACE the player line and game loop with:',
      '',
      '    player = pygame.Rect(80, 100, 38, 54)   # start in the air so we see gravity',
      '    vx = 0; vy = 0',
      '    GROUND_Y = 478',
      '    while True:',
      '        for event in pygame.event.get():',
      '            if event.type == pygame.QUIT: pygame.quit(); sys.exit()',
      '        keys = pygame.key.get_pressed()',
      '        vx = 0',
      '        if keys[pygame.K_LEFT]:  vx = -5',
      '        if keys[pygame.K_RIGHT]: vx = 5',
      '        vy = min(18, vy + 0.72)   # gravity',
      '        player.x += vx',
      '        player.y += vy',
      '        if player.bottom > GROUND_Y:',
      '            player.bottom = GROUND_Y',
      '            vy = 0',
      '        # (drawing block from S1 stays the same)',
      '',
      'RUN IT. Player drops from the sky onto the grass. Then LEFT/RIGHT slide them around. Walk off the edge of the screen — they keep going forever (we fix that next).',
      '',
      'WHY min(18, ...): without it, vy keeps growing forever and after a long fall the player would tunnel THROUGH the ground in one frame. 18 pixels per frame is fast enough but still catchable by the collision check.',
      '',
      'TRY THIS: Change gravity from 0.72 to 0.2 (moon gravity — floats slowly) and then to 1.5 (heavy planet). Change move speed from 5 to 12 — too fast! Find a fair speed.',
    ].join('\n'),
  },

  // S3
  {
    step_number: 3,
    title: 'Section 3: Today add JUMP with the space bar (and stop falling off the edge)',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-3', 'jump', 'platforms'],
    content: [
      'TODAY: Press SPACE to jump — but only when standing on the ground. Add 3 floating stone platforms the player can land on. Add screen edges.',
      '',
      'WHY: A jump is just "set vy to a big negative number" (negative = upward because y=0 is the top). The on_ground flag stops infinite double-jumps.',
      '',
      'ADD above the loop:',
      '',
      '    on_ground = False',
      '    platforms = [pygame.Rect(0, 478, 960, 80),       # the main ground',
      '                 pygame.Rect(260, 392, 190, 26),     # floating stone 1',
      '                 pygame.Rect(560, 330, 210, 26),     # floating stone 2',
      '                 pygame.Rect(820, 270, 120, 26)]     # floating stone 3',
      '',
      'REPLACE the gravity + ground-clamp block with proper platform collision:',
      '',
      '    if keys[pygame.K_SPACE] and on_ground:',
      '        vy = -15.2',
      '        on_ground = False',
      '    vy = min(18, vy + 0.72)',
      '    player.x += vx',
      '    for p in platforms:',
      '        if player.colliderect(p):',
      '            if vx > 0: player.right = p.left',
      '            elif vx < 0: player.left = p.right',
      '    player.y += vy',
      '    on_ground = False',
      '    for p in platforms:',
      '        if player.colliderect(p):',
      '            if vy > 0:',
      '                player.bottom = p.top',
      '                on_ground = True; vy = 0',
      '            elif vy < 0:',
      '                player.top = p.bottom; vy = 0',
      '    player.x = max(0, min(player.x, 960 - player.width))   # screen edge',
      '',
      'DRAW the platforms (before drawing the player):',
      '',
      '    for p in platforms[1:]:   # skip the ground (already drawn)',
      '        pygame.draw.rect(screen, (92, 100, 128), p, border_radius=4)',
      '',
      'RUN IT. Jump with SPACE. Land on the stones. Jump off the stones. The player cannot leave the screen sideways.',
      '',
      'WHY MOVE X AND Y SEPARATELY: doing player.x += vx FIRST, checking horizontal collisions, THEN player.y += vy and checking vertical collisions, makes it possible to walk INTO a wall without sticking to it. Move both at once and the collision math gets messy.',
      '',
      'TRY THIS: Change JUMP from -15.2 to -25 (mega-jump!) and then to -8 (sad little hop). Add a 4th platform somewhere new — say pygame.Rect(700, 200, 120, 26).',
    ].join('\n'),
  },

  // S4
  {
    step_number: 4,
    title: 'Section 4: Today the HAND moves the player (camera in the corner)',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-4', 'mediapipe', 'gesture-controls'],
    content: [
      'TODAY: Plug in the webcam. Move your hand LEFT — player walks left. RIGHT — player walks right. A small preview of the camera appears in the top corner so you can see what the camera sees.',
      '',
      'WHY: We map the hand\'s horizontal position (0 to 1) to a movement axis (-1 to +1). Hand on the left half = walk left. Hand on the right half = walk right. Centre = stand still.',
      '',
      'ADD at top:',
      '',
      '    import cv2, mediapipe as mp',
      '    mp_hands = mp.solutions.hands',
      '    camera = cv2.VideoCapture(0)',
      '    hands = mp_hands.Hands(max_num_hands=1)',
      '    smoothed_x = None',
      '',
      'INSIDE the loop, REPLACE the vx assignment with:',
      '',
      '    move_axis = 0',
      '    ok, frame = camera.read()',
      '    if ok:',
      '        frame = cv2.flip(frame, 1)',
      '        rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)',
      '        result = hands.process(rgb)',
      '        if result.multi_hand_landmarks:',
      '            hand_x = result.multi_hand_landmarks[0].landmark[9].x',
      '            smoothed_x = hand_x if smoothed_x is None else smoothed_x*0.66 + hand_x*0.34',
      '            offset = smoothed_x - 0.5',
      '            if abs(offset) > 0.13:                            # dead zone',
      '                move_axis = max(-1, min(1, offset / 0.32))',
      '        # show small preview in corner',
      '        prev = cv2.resize(frame, (180, 135))',
      '        prev = cv2.cvtColor(prev, cv2.COLOR_BGR2RGB)',
      '        prev_surface = pygame.image.frombuffer(prev.tobytes(), (180,135), "RGB")',
      '        screen.blit(prev_surface, (770, 10))',
      '    if keys[pygame.K_LEFT]:  move_axis = -1   # keyboard still works',
      '    if keys[pygame.K_RIGHT]: move_axis = 1',
      '    vx = move_axis * 5',
      '',
      'RUN IT. Hold your hand in front of the camera. Move it left — player walks left. Centre your hand — player stops. You can also still use arrow keys when camera is off.',
      '',
      'THE DEAD ZONE: abs(offset) > 0.13 means "only move if the hand is at least 13% off centre". Without it, tiny shakes make the player jitter. Try removing the dead zone to feel the difference.',
      '',
      'TRY THIS: Change 0.13 to 0.05 — super sensitive. Then 0.30 — sluggish. Find what feels right for your camera setup. Also try landmark[9] → landmark[8] (index fingertip instead of palm centre). Which feels better for moving?',
    ].join('\n'),
  },

  // S5
  {
    step_number: 5,
    title: 'Section 5: Today OPEN PALM = JUMP (no more space bar)',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-5', 'gestures', 'edge-trigger'],
    content: [
      'TODAY: Add the gesture: ALL FOUR FINGERS UP (open palm) = jump. We use the same edge-trigger trick from DJ Session 6 so each palm-show jumps once, not 60 times in a row.',
      '',
      'WHY: Now the game is hands-only. You move with hand position, jump with open palm. Feels magical to the kid.',
      '',
      'ADD a helper at the top:',
      '',
      '    def finger_up(lms, tip, pip): return lms[tip].y < lms[pip].y - 0.015',
      '',
      'ADD above the loop:',
      '',
      '    palm_was_open = False',
      '',
      'INSIDE the camera branch, AFTER you compute smoothed_x, ADD:',
      '',
      '    lms = result.multi_hand_landmarks[0].landmark',
      '    palm_open = (finger_up(lms,8,6) and finger_up(lms,12,10)',
      '                 and finger_up(lms,16,14) and finger_up(lms,20,18))',
      '    if palm_open and not palm_was_open and on_ground:',
      '        vy = -15.2',
      '        on_ground = False',
      '    palm_was_open = palm_open',
      '',
      'You can REMOVE the keyboard SPACE jump if you want — or keep it as a backup.',
      '',
      'RUN IT. Walk with hand. JUMP by showing an open palm to the camera. Try to land on the top stone platform.',
      '',
      'WHY EDGE TRIGGER AGAIN: palm_open and not palm_was_open means "this is the first frame the palm just opened". The palm stays open for many frames. Without the edge trigger, the player would spam-jump every frame the palm is open.',
      '',
      'TRY THIS: Make the jump weaker for palm-jumps (vy = -10) and keep SPACE for a stronger jump (vy = -15.2) — so the kid has two kinds of jump. Or: change the gesture from "open palm" to "thumbs up" (only thumb up, all others down — landmarks index 4 + check fingers).',
    ].join('\n'),
  },

  // S6
  {
    step_number: 6,
    title: 'Section 6: Today add COINS to collect and ENEMIES to dodge',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-6', 'collectibles', 'enemies'],
    content: [
      'TODAY: Yellow coins on platforms — touching = +25 score. Walking enemies on the ground — touching them = lose 1 life, but JUMPING ONTO their head = kill them and bounce.',
      '',
      'WHY: This is the classic Mario rule. Same colliderect logic we used for platforms, plus a "am I falling onto them?" check.',
      '',
      'ADD above the loop:',
      '',
      '    from dataclasses import dataclass',
      '    @dataclass',
      '    class Coin:',
      '        x: int; y: int; collected: bool = False',
      '    @dataclass',
      '    class Enemy:',
      '        x: float; y: float; left: int; right: int; vx: float = 1.5; alive: bool = True',
      '        @property',
      '        def rect(self): return pygame.Rect(int(self.x), int(self.y), 42, 34)',
      '',
      '    coins = [Coin(310, 360), Coin(610, 300), Coin(840, 240)]',
      '    enemies = [Enemy(520, 478-34, 470, 690), Enemy(180, 478-34, 100, 320, -1.4)]',
      '    score = 0; lives = 3; invincible_until = 0',
      '',
      'INSIDE the loop, AFTER the platform collision code, ADD:',
      '',
      '    import time',
      '    for c in coins:',
      '        if not c.collected and player.colliderect(pygame.Rect(c.x-16, c.y-16, 32, 32)):',
      '            c.collected = True; score += 25',
      '    for e in enemies:',
      '        if not e.alive: continue',
      '        e.x += e.vx',
      '        if e.x <= e.left or e.x + 42 >= e.right: e.vx *= -1',
      '        if player.colliderect(e.rect):',
      '            falling = vy > 2 and player.bottom - e.rect.top < 20',
      '            if falling:',
      '                e.alive = False; vy = -10; score += 100',
      '            elif time.time() > invincible_until:',
      '                lives -= 1; invincible_until = time.time() + 1.4',
      '                vy = -8; vx = -5',
      '',
      'DRAW coins and enemies (before drawing the player):',
      '',
      '    for c in coins:',
      '        if not c.collected: pygame.draw.circle(screen, (255,225,64), (c.x, c.y), 11)',
      '    for e in enemies:',
      '        if e.alive: pygame.draw.rect(screen, (255,90,85), e.rect, border_radius=6)',
      '    font = pygame.font.SysFont(None, 36)',
      '    screen.blit(font.render(f"SCORE {score}  LIVES {lives}", True, (245,244,255)), (16, 12))',
      '',
      'RUN IT. Pick up coins. Stomp enemies. Try to die on purpose by walking into one — lose a life and bounce backward.',
      '',
      'THE STOMP CHECK: vy > 2 means "we are moving downward fast" and player.bottom - e.rect.top < 20 means "our feet are roughly at the enemy\'s head". Both true = stomp. Either false = damage.',
      '',
      'TRY THIS: Add 3 more coins in spots that feel hard to reach. Add a third enemy that walks on top of the stone platform — pygame.Rect(560, 330, 210, 26) is the platform, so enemy at y = 330-34 = 296, left=560 right=770.',
    ].join('\n'),
  },

  // S7
  {
    step_number: 7,
    title: 'Section 7: Today PINCH shoots a fireball to kill enemies from a distance',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-7', 'projectiles', 'gesture-attack'],
    content: [
      'TODAY: Pinch thumb + index = SHOOT a cyan fireball in the direction the player is facing. Fireballs travel, hit walls, hit enemies. This is your ranged attack.',
      '',
      'WHY: A projectile is just another moving rectangle with a position and a speed. It checks against platforms (stops on wall) and enemies (kills them). Same patterns as everything else.',
      '',
      'ADD a Fireball dataclass:',
      '',
      '    @dataclass',
      '    class Fireball:',
      '        x: float; y: float; vx: float; life: float = 1.35',
      '        @property',
      '        def rect(self): return pygame.Rect(int(self.x-10), int(self.y-10), 20, 20)',
      '',
      'ADD above the loop:',
      '',
      '    fireballs = []; facing = 1; was_pinching = False; shoot_ready_at = 0',
      '    def distance(a,b):',
      '        import math; return math.hypot(a[0]-b[0], a[1]-b[1])',
      '',
      'INSIDE the camera branch (you already have lms), ADD:',
      '',
      '    index_pt = (lms[8].x, lms[8].y)',
      '    thumb_pt = (lms[4].x, lms[4].y)',
      '    pinching = distance(index_pt, thumb_pt) < 0.06',
      '    if pinching and not was_pinching and time.time() > shoot_ready_at:',
      '        shoot_ready_at = time.time() + 0.32',
      '        fireballs.append(Fireball(player.centerx + facing*26, player.centery - 6, 10.5*facing))',
      '    was_pinching = pinching',
      '',
      'After vx is set, update facing:',
      '',
      '    if abs(vx) > 0.5:  facing = 1 if vx > 0 else -1',
      '',
      'After enemies loop, ADD fireball update:',
      '',
      '    kept = []',
      '    for fb in fireballs:',
      '        fb.x += fb.vx; fb.life -= 1/60',
      '        if fb.life <= 0: continue',
      '        hit_wall = any(fb.rect.colliderect(p) for p in platforms)',
      '        if hit_wall: continue',
      '        hit_enemy = False',
      '        for e in enemies:',
      '            if e.alive and fb.rect.colliderect(e.rect):',
      '                e.alive = False; score += 100; hit_enemy = True; break',
      '        if not hit_enemy: kept.append(fb)',
      '    fireballs = kept',
      '    for fb in fireballs:',
      '        pygame.draw.circle(screen, (80, 245, 255), (int(fb.x), int(fb.y)), 8)',
      '',
      'RUN IT. Walk to the right (face right). Pinch — a cyan fireball flies right. Hit an enemy from a safe distance.',
      '',
      'THE 0.06 PINCH THRESHOLD: index_pt and thumb_pt here are still in 0-to-1 fractional coordinates from MediaPipe (we did NOT multiply by width/height yet). So a "close" pinch is around 6% of the frame width. If your pinch is not triggering, raise to 0.08.',
      '',
      'TRY THIS: Make fireballs go faster (10.5 → 18). Make them last longer (life=1.35 → 3.0). Add a delay between shots: change 0.32 to 0.8 — now you cannot spam.',
    ].join('\n'),
  },

  // S8
  {
    step_number: 8,
    title: 'Section 8: Showcase — goal flag, win screen, dash, speedrun!',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-8', 'polish', 'showcase'],
    content: [
      'TODAY: Add a green GOAL flag at the far right. Touching it = WIN. Add a "two-fingers up" gesture for DASH (run faster). Then the class does a SPEEDRUN tournament.',
      '',
      'WHY: A game needs an END. The goal makes every coin and every kill feel like part of a journey. The dash gesture rewards mastery — and is just one extra if.',
      '',
      'ADD a goal flag (in the platforms drawing block, or its own block):',
      '',
      '    GOAL_X = 900',
      '    pygame.draw.rect(screen, (92, 230, 120), (GOAL_X, 420, 8, 58))',
      '    pygame.draw.polygon(screen, (92,230,120),',
      '                        [(GOAL_X+8, 420), (GOAL_X+50, 432), (GOAL_X+8, 444)])',
      '',
      'ADD above the loop:',
      '',
      '    won = False',
      '',
      'INSIDE the loop (after coin/enemy logic):',
      '',
      '    if player.centerx >= GOAL_X and not won:',
      '        won = True; score += 500',
      '',
      'DASH GESTURE — inside the camera branch, after computing palm_open:',
      '',
      '    two_fingers = finger_up(lms,8,6) and finger_up(lms,12,10) and not finger_up(lms,16,14) and not finger_up(lms,20,18)',
      '    speed = 7.4 if two_fingers else 5',
      '    vx = move_axis * speed   # replace the old "vx = move_axis * 5" with this',
      '',
      'WIN SCREEN — at the end of the drawing block:',
      '',
      '    if won:',
      '        big = pygame.font.SysFont(None, 96)',
      '        screen.blit(big.render("YOU WIN!", True, (92,230,120)), (340, 220))',
      '        screen.blit(font.render(f"Final score: {score}  -  Press R to play again", True, (245,244,255)), (270, 320))',
      '    if lives <= 0:',
      '        screen.blit(font.render("GAME OVER - Press R to retry", True, (255,90,85)), (300, 270))',
      '',
      'AND in the event loop, ADD restart:',
      '',
      '        if event.type == pygame.KEYDOWN and event.key == pygame.K_r:',
      '            player.x = 80; player.y = 100; vx = vy = 0',
      '            score = 0; lives = 3; won = False',
      '            for c in coins: c.collected = False',
      '            for e in enemies: e.alive = True',
      '            fireballs.clear()',
      '',
      'RUN IT. Hand to move, palm to jump, pinch to shoot, two-fingers to dash, reach the green flag = WIN.',
      '',
      'TODAY\'S CLASSROOM TRY: SPEEDRUN tournament. Each student plays one full run. Fastest time to the goal wins. Highest coin count wins separately. Most enemies stomped wins a third prize. Everyone gets a category.',
      '',
      'TRYOUT FOR HOME: 1) Add a 2nd level — when the player wins, instead of showing YOU WIN, reset the player to x=80 but make all enemies twice as fast. 2) BIG CHALLENGE: scroll the camera. Right now the level is 960 wide (one screen). Look at the real gesture_platformer.py for how camera_x and LEVEL_WIDTH are used — and copy that pattern to make the level 2000 wide, scrolling as the player moves right.',
    ].join('\n'),
  },
];

const resolveTargetClass = async () => {
  const r = await pool.query(
    `SELECT class_name, grade FROM learning_projects WHERE class_name = $1 AND is_active = true LIMIT 1`,
    [FALLBACK_CLASS_NAME]
  );
  if (r.rows[0]) return { class_name: r.rows[0].class_name, grade: r.rows[0].grade || FALLBACK_CLASS_NAME };
  console.warn(`⚠️  No existing "${FALLBACK_CLASS_NAME}" project found — creating fresh.`);
  return { class_name: FALLBACK_CLASS_NAME, grade: FALLBACK_CLASS_NAME };
};

const seed = async () => {
  await createLearningTables();
  const { class_name, grade } = await resolveTargetClass();
  console.log(`📚 Assigning "${PROJECT_TITLE}" to class: ${class_name}`);
  const project = await createLearningProject({
    title: PROJECT_TITLE,
    subject: 'Game Programming, Python, Computer Vision',
    grade,
    class_name,
    description:
      'An 8-section project where students build a Super-Mario-style platformer controlled by hand gestures. Each session adds one runnable layer — pygame window, gravity + keys, jumping + platforms, hand-driven movement, palm-to-jump, coins + enemies, pinch-to-shoot, goal + dash + win screen. Last session is a class speedrun tournament.',
    learning_goals:
      'Build a pygame window with a game clock, implement gravity and rectangle-on-rectangle collision separately on x and y, manage on-ground state for jumping, plug a webcam into a non-OpenCV game and use MediaPipe gestures as inputs, use edge-triggered gestures for one-shot actions, fire projectiles, design a scoring + lives + win/lose loop.',
    difficulty_level: 'intermediate',
    duration_months: 2,
    expected_section_count: SECTION_COUNT,
    audience_scope: 'student_teacher',
    teacher_readiness_required: false,
    code_explanation_required: true,
    source_doc_name: 'hand_gesture_platformer/gesture_platformer.py',
    created_by_role: 'system',
  });
  const created = await replaceLearningContentChunks(project.id, chunks);
  return { project, class_name, chunk_count: created.length, sessions: SECTION_COUNT };
};

seed()
  .then((r) => { console.log('✅ Star Leap Gesture Platformer learning project seeded'); console.log(JSON.stringify(r, null, 2)); })
  .catch((e) => { console.error('❌ Failed to seed Star Leap Gesture Platformer project:', e.message); process.exitCode = 1; })
  .finally(async () => { await pool.end(); });
