/*
 * Seed: Hand Gesture Arcade
 *
 * Real per-session lesson content (no roadmap). 7 one-hour sessions. Each
 * session ends with a runnable mini-program the kid types in class, plus a
 * "Try this" tryout.
 *
 * Run with:   node backend/scripts/seedHandGestureArcadeProject.js
 */

const pool = require('../src/config/db');
const {
  createLearningTables,
  createLearningProject,
  replaceLearningContentChunks,
} = require('../src/models/learningModel');

const PROJECT_TITLE = 'Hand Gesture Arcade';
const FALLBACK_CLASS_NAME = 'JHS 1';
const SECTION_COUNT = 7;

const chunks = [
  // ── Project-wide setup ─────────────────────────────────────────────────────
  {
    title: 'Before we start: what you need on the laptop',
    source_type: 'setup',
    audience: 'both',
    tags: ['setup', 'python', 'install'],
    content: [
      'For this game you need Python 3.11 or 3.12 (not 3.14). In Terminal:',
      '',
      '    cd hand_gesture_arcade',
      '    python3.11 -m venv .venv',
      '    source .venv/bin/activate',
      '    pip install opencv-python mediapipe numpy',
      '',
      'Create one file called gesture_arcade.py — every session adds to it. Run with python gesture_arcade.py. Press Q in the window to quit, R to restart later.',
    ].join('\n'),
  },

  // S1
  {
    step_number: 1,
    title: 'Section 1: Today the camera tracks your finger',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-1', 'mediapipe', 'cursor'],
    content: [
      'TODAY: We get a glowing cyan dot to follow your index finger. By the end of class you can move the dot anywhere on screen with your hand.',
      '',
      'WHY: The dot is the "player". Catching stars, dodging bombs, exploding things — all of it is just "what is happening at the dot?". So we need the dot moving smoothly first.',
      '',
      'TYPE THIS into gesture_arcade.py:',
      '',
      '    import cv2, numpy as np, mediapipe as mp',
      '    mp_hands = mp.solutions.hands',
      '    camera = cv2.VideoCapture(0)',
      '    with mp_hands.Hands(max_num_hands=1) as hands:',
      '        while True:',
      '            ok, frame = camera.read()',
      '            if not ok: break',
      '            frame = cv2.flip(frame, 1)',
      '            display = cv2.addWeighted(frame, 0.25, np.zeros_like(frame), 0.75, 0)',
      '            result = hands.process(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))',
      '            if result.multi_hand_landmarks:',
      '                h, w = frame.shape[:2]',
      '                lm = result.multi_hand_landmarks[0].landmark[8]',
      '                pt = (int(lm.x * w), int(lm.y * h))',
      '                cv2.circle(display, pt, 28, (255, 255, 0), -1)',
      '                cv2.circle(display, pt, 46, (255, 255, 0), 2)',
      '            cv2.imshow("Arcade", display)',
      '            if cv2.waitKey(1) & 0xFF == ord("q"): break',
      '    camera.release(); cv2.destroyAllWindows()',
      '',
      'RUN IT. A glowing cyan dot follows your index finger over a dimmed mirror of yourself.',
      '',
      'WHY THE DIM BACKGROUND: cv2.addWeighted(frame, 0.25, black, 0.75, 0) blends only 25% of the real camera onto a black image. The game feels more arcade-like when the world is dark and the action glows.',
      '',
      'TRY THIS: Make the dot bigger (change 28 → 50). Then make it pink (255, 80, 255). Then dim the camera more (0.25 → 0.1). Which combination feels most like an arcade?',
    ].join('\n'),
  },

  // S2
  {
    step_number: 2,
    title: 'Section 2: Today a single star falls from the top of the screen',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-2', 'animation', 'falling-object'],
    content: [
      'TODAY: We add one yellow star that falls from the top. Every frame, its Y position grows. When it reaches the bottom, it disappears.',
      '',
      'WHY: Every falling thing in the final game (stars, gems, bombs) works the same way — a position and a downward speed. Doing it once with ONE star is the cleanest way to learn it.',
      '',
      'ADD this above the while loop:',
      '',
      '    star_x = 400',
      '    star_y = -30',
      '    star_speed = 4',
      '',
      'INSIDE the loop, BEFORE cv2.imshow, add:',
      '',
      '    star_y += star_speed',
      '    if star_y > display.shape[0] + 40:',
      '        star_y = -30   # respawn at the top',
      '        star_x = np.random.randint(80, display.shape[1]-80)',
      '    cv2.circle(display, (star_x, int(star_y)), 26, (0, 245, 255), -1)',
      '    cv2.circle(display, (star_x, int(star_y)), 26, (255, 255, 255), 2)',
      '',
      'RUN IT. A yellow star keeps falling from random horizontal spots. Your cyan finger-dot is still there too.',
      '',
      'WHAT IS HAPPENING: star_y += star_speed means "next frame the star is 4 pixels lower". When star_y goes off the bottom, we put it back above the top and pick a new random x. That is how you get an endless stream from just ONE star.',
      '',
      'TRY THIS: Change star_speed to 12. Too fast? Try 2 — too slow? Find a speed that feels fair. Then try making the star pink instead of yellow.',
    ].join('\n'),
  },

  // S3
  {
    step_number: 3,
    title: 'Section 3: Today catching the star scores points',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-3', 'collision', 'score'],
    content: [
      'TODAY: When your finger-dot touches the star, the star vanishes and your score goes up. Now we have a real game loop.',
      '',
      'WHY: "Touching" in code is just distance. If the distance between two points is small enough, they are touching. This idea is in every game ever made.',
      '',
      'ADD a tiny distance helper at the top (after imports):',
      '',
      '    import math',
      '    def distance(a, b):',
      '        return math.hypot(a[0]-b[0], a[1]-b[1])',
      '',
      'ADD above the while loop:',
      '',
      '    score = 0',
      '',
      'INSIDE the loop, REPLACE your star-drawing block with:',
      '',
      '    star_y += star_speed',
      '    cursor = pt if result.multi_hand_landmarks else None',
      '    star_pos = (star_x, int(star_y))',
      '    if cursor is not None and distance(cursor, star_pos) < 50:',
      '        score += 10',
      '        star_y = -30',
      '        star_x = np.random.randint(80, display.shape[1]-80)',
      '    elif star_y > display.shape[0] + 40:',
      '        star_y = -30',
      '        star_x = np.random.randint(80, display.shape[1]-80)',
      '    cv2.circle(display, star_pos, 26, (0, 245, 255), -1)',
      '    cv2.circle(display, star_pos, 26, (255, 255, 255), 2)',
      '    cv2.putText(display, f"SCORE {score}", (20, 50),',
      '                cv2.FONT_HERSHEY_SIMPLEX, 1.2, (255, 255, 255), 3)',
      '',
      'RUN IT. Catch the star with your finger. SCORE 10. Catch again. SCORE 20. The game has begun!',
      '',
      'THE COLLISION RULE: distance(cursor, star_pos) < 50 means "if the finger is within 50 pixels of the star". 50 is the "hitbox". Smaller number = harder game.',
      '',
      'TRY THIS: Change < 50 to < 20 — much harder to catch! Then try < 120 — way too easy. Find the number that makes the game feel fair.',
    ].join('\n'),
  },

  // S4
  {
    step_number: 4,
    title: 'Section 4: Today add bombs — touching them costs a heart',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-4', 'enemies', 'hearts'],
    content: [
      'TODAY: Add a falling red bomb. Touching it = lose 1 heart out of 3. When hearts hit 0, GAME OVER appears.',
      '',
      'WHY: Stakes make games fun. Catch the good stuff, AVOID the bad stuff. Same falling code as the star, different colour, different effect.',
      '',
      'ADD above the while loop:',
      '',
      '    bomb_x = 600',
      '    bomb_y = -200',
      '    hearts = 3',
      '    game_over = False',
      '',
      'INSIDE the loop, ABOVE your star block, add:',
      '',
      '    if not game_over:',
      '        bomb_y += 5',
      '        bomb_pos = (bomb_x, int(bomb_y))',
      '        if cursor is not None and distance(cursor, bomb_pos) < 45:',
      '            hearts -= 1',
      '            bomb_y = -200',
      '            bomb_x = np.random.randint(80, display.shape[1]-80)',
      '        elif bomb_y > display.shape[0] + 40:',
      '            bomb_y = -200',
      '            bomb_x = np.random.randint(80, display.shape[1]-80)',
      '        cv2.circle(display, bomb_pos, 24, (70, 80, 255), -1)',
      '        cv2.circle(display, bomb_pos, 24, (255, 255, 255), 2)',
      '        if hearts <= 0:',
      '            game_over = True',
      '    cv2.putText(display, "HEARTS " + "|" * max(0, hearts), (280, 50),',
      '                cv2.FONT_HERSHEY_SIMPLEX, 1.0, (70, 80, 255), 3)',
      '    if game_over:',
      '        cv2.putText(display, "GAME OVER", (display.shape[1]//2 - 180, display.shape[0]//2),',
      '                    cv2.FONT_HERSHEY_SIMPLEX, 2.0, (255, 80, 255), 4)',
      '',
      'RUN IT. Stars are still your friends. Bombs are bad — dodge them. Lose 3 hearts and the game ends.',
      '',
      'HEART STRING TRICK: "|" * 3 in Python gives "|||". So "HEARTS " + "|" * hearts shows three vertical bars when hearts=3, two when hearts=2, none when hearts=0. Way cleaner than drawing tiny heart images.',
      '',
      'TRY THIS: Make bombs FASTER than stars (bomb_y += 8). Or change the bomb to draw a red square instead of a circle: use cv2.rectangle. Hint: cv2.rectangle(display, (bomb_pos[0]-24, bomb_pos[1]-24), (bomb_pos[0]+24, bomb_pos[1]+24), color, -1)',
    ].join('\n'),
  },

  // S5
  {
    step_number: 5,
    title: 'Section 5: Today MANY things fall at once — using a list',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-5', 'lists', 'dataclass'],
    content: [
      'TODAY: One star is boring. We replace our single star/bomb with a LIST of falling items, each with its own x, y, speed, kind, colour. New items spawn over time.',
      '',
      'WHY: A list lets us have 20 things on screen with the SAME code that handles one. Every game engine does this.',
      '',
      'ADD at top of file:',
      '',
      '    import random, time',
      '    from dataclasses import dataclass',
      '    @dataclass',
      '    class FallingItem:',
      '        x: float',
      '        y: float',
      '        vy: float',
      '        kind: str   # "star" or "bomb"',
      '        color: tuple',
      '        points: int',
      '',
      'REPLACE the bomb_x / bomb_y / star_x / star_y stuff with:',
      '',
      '    items = []',
      '    last_spawn = time.time()',
      '    score = 0',
      '    hearts = 3',
      '    game_over = False',
      '',
      'INSIDE the loop, REPLACE the star-block and bomb-block with:',
      '',
      '    if not game_over and time.time() - last_spawn > 0.7:',
      '        last_spawn = time.time()',
      '        if random.random() < 0.25:',
      '            items.append(FallingItem(random.randint(80, display.shape[1]-80), -30, 6, "bomb", (70,80,255), 0))',
      '        else:',
      '            items.append(FallingItem(random.randint(80, display.shape[1]-80), -30, 5, "star", (0,245,255), 10))',
      '    keep = []',
      '    for it in items:',
      '        it.y += it.vy',
      '        pos = (int(it.x), int(it.y))',
      '        touched = cursor is not None and distance(cursor, pos) < 50',
      '        if touched:',
      '            if it.kind == "bomb":',
      '                hearts -= 1',
      '                if hearts <= 0: game_over = True',
      '            else:',
      '                score += it.points',
      '            continue',
      '        if it.y > display.shape[0] + 40:',
      '            continue',
      '        keep.append(it)',
      '        cv2.circle(display, pos, 26, it.color, -1)',
      '        cv2.circle(display, pos, 26, (255,255,255), 2)',
      '    items = keep',
      '',
      'RUN IT. A steady stream of stars and bombs now falls. The game finally feels alive.',
      '',
      'WHY @dataclass: It saves typing. Instead of writing an __init__, @dataclass auto-generates one. FallingItem(x=100, y=0, vy=5, kind="star", color=..., points=10) just works.',
      '',
      'TRY THIS: Add a third kind called "gem" worth 25 points (purple colour, say (255, 80, 200)). Change the spawn block so 10% of items are gems. Hint: another elif inside the spawn block.',
    ].join('\n'),
  },

  // S6
  {
    step_number: 6,
    title: 'Section 6: Today add particle explosions when you catch something',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-6', 'particles', 'animation'],
    content: [
      'TODAY: When you catch a star, 20 tiny dots fly out from the spot and fade away. This is what makes the game feel "juicy".',
      '',
      'WHY: Particles use exactly the same falling-item idea, but with random directions and a "life" that counts down. Same pattern, new feeling.',
      '',
      'ADD a Particle dataclass at the top:',
      '',
      '    @dataclass',
      '    class Particle:',
      '        x: float',
      '        y: float',
      '        vx: float',
      '        vy: float',
      '        life: float',
      '        color: tuple',
      '',
      'ADD above the loop:',
      '',
      '    particles = []',
      '    def burst(center, color, n=24):',
      '        for _ in range(n):',
      '            angle = random.uniform(0, math.tau)',
      '            speed = random.uniform(2, 10)',
      '            particles.append(Particle(center[0], center[1], math.cos(angle)*speed, math.sin(angle)*speed, 30, color))',
      '',
      'INSIDE the touched-block, AFTER score += or hearts -= add:',
      '',
      '    burst(pos, it.color, 28)',
      '',
      'INSIDE the loop, AFTER the items loop, add:',
      '',
      '    alive = []',
      '    for p in particles:',
      '        p.x += p.vx; p.y += p.vy',
      '        p.vx *= 0.96; p.vy *= 0.96',
      '        p.life -= 1',
      '        if p.life > 0:',
      '            cv2.circle(display, (int(p.x), int(p.y)), 3, p.color, -1)',
      '            alive.append(p)',
      '    particles = alive',
      '',
      'RUN IT. Catch a star — fireworks! Catch a gem — bigger fireworks (if you used purple in S5). Touch a bomb — red explosion + heart lost.',
      '',
      'WHY THE *= 0.96: vx *= 0.96 makes the particle 4% slower every frame, like air friction. Without it the particles fly forever and look ugly.',
      '',
      'TRY THIS: Change burst count from 28 to 60 — much more dramatic. Then try 8 — too sad. Find a number that feels right.',
    ].join('\n'),
  },

  // S7
  {
    step_number: 7,
    title: 'Section 7: Today the showcase — timer, combo, restart, high score',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-7', 'polish', 'showcase'],
    content: [
      'TODAY: We finish the game. Add a 60-second timer, a combo counter (catching in a row = bonus), a GAME OVER screen, and an R key to restart. Then we do a class high-score competition.',
      '',
      'WHY: Replayability is what turns a demo into a game. Timer + restart + combo = "one more try!"',
      '',
      'ADD above the loop:',
      '',
      '    GAME_SECONDS = 60',
      '    combo = 0',
      '    started_at = time.time()',
      '',
      'INSIDE the touched-block FOR STARS/GEMS only, replace score += it.points with:',
      '',
      '    combo += 1',
      '    bonus = min(20, combo * 2)',
      '    score += it.points + bonus',
      '',
      'INSIDE the bomb branch:',
      '',
      '    combo = 0',
      '',
      'INSIDE the loop, BEFORE the spawn block, add the timer check:',
      '',
      '    remaining = int(GAME_SECONDS - (time.time() - started_at))',
      '    if remaining <= 0 or hearts <= 0:',
      '        game_over = True',
      '',
      'ADD to the HUD line:',
      '',
      '    cv2.putText(display, f"TIME {max(0, remaining)}", (520, 50),',
      '                cv2.FONT_HERSHEY_SIMPLEX, 1.0, (0, 245, 255), 3)',
      '    cv2.putText(display, f"COMBO x{combo}", (700, 50),',
      '                cv2.FONT_HERSHEY_SIMPLEX, 1.0, (255, 255, 0), 3)',
      '',
      'ADD inside the key handling at the bottom:',
      '',
      '    if key == ord("r"):',
      '        items.clear(); particles.clear()',
      '        score = 0; hearts = 3; combo = 0',
      '        started_at = time.time(); game_over = False',
      '',
      'RUN IT. 60 seconds. Catch as much as you can. Build a combo. Avoid bombs. Press R after GAME OVER. Try again.',
      '',
      'TODAY\'S CLASSROOM TRY: 3-minute "free practice" then a TOURNAMENT. Every student plays one 60-second round. Teacher writes scores on the board. Highest combo also gets a prize.',
      '',
      'TRYOUT FOR HOME: 1) Try adding a "speed up over time" — change spawn interval from 0.7 to max(0.25, 0.7 - (time.time()-started_at)*0.01) so items come faster as time runs out. 2) BONUS: add a pinch-blast that destroys all items on screen at once. Hint: detect pinching like in Name Writer Session 4, and when you do, loop over items and clear all of them (give some bonus points each).',
    ].join('\n'),
  },
];

// ── Resolve class ────────────────────────────────────────────────────────────
const resolveTargetClass = async () => {
  const result = await pool.query(
    `SELECT class_name, grade
       FROM learning_projects
      WHERE class_name = $1 AND is_active = true
      LIMIT 1`,
    [FALLBACK_CLASS_NAME]
  );
  if (result.rows[0]) {
    return { class_name: result.rows[0].class_name, grade: result.rows[0].grade || FALLBACK_CLASS_NAME };
  }
  console.warn(`⚠️  No existing "${FALLBACK_CLASS_NAME}" project found — creating fresh.`);
  return { class_name: FALLBACK_CLASS_NAME, grade: FALLBACK_CLASS_NAME };
};

const seed = async () => {
  await createLearningTables();
  const { class_name, grade } = await resolveTargetClass();
  console.log(`📚 Assigning "${PROJECT_TITLE}" to class: ${class_name}`);

  const project = await createLearningProject({
    title: PROJECT_TITLE,
    subject: 'Computer Vision, Python, Game Programming',
    grade,
    class_name,
    description:
      'A 7-section project where students build a falling-objects arcade game controlled by hand gestures. Each session adds one runnable piece — cursor, falling item, scoring, bombs, lists, particles, polish — and ends with the game in a more fun state than it started. Last session is a class tournament.',
    learning_goals:
      'Track a fingertip cursor, animate falling objects, detect circle-circle collisions, use Python lists and dataclasses to manage many items, build particle effects from random angles and life counters, add timers and combo systems, and design a restartable game loop.',
    difficulty_level: 'beginner',
    duration_months: 2,
    expected_section_count: SECTION_COUNT,
    audience_scope: 'student_teacher',
    teacher_readiness_required: false,
    code_explanation_required: true,
    source_doc_name: 'hand_gesture_arcade/gesture_arcade.py',
    created_by_role: 'system',
  });

  const createdChunks = await replaceLearningContentChunks(project.id, chunks);
  return { project, class_name, chunk_count: createdChunks.length, sessions: SECTION_COUNT };
};

seed()
  .then((r) => { console.log('✅ Hand Gesture Arcade learning project seeded'); console.log(JSON.stringify(r, null, 2)); })
  .catch((e) => { console.error('❌ Failed to seed Hand Gesture Arcade project:', e.message); process.exitCode = 1; })
  .finally(async () => { await pool.end(); });
