/*
 * Seed: Hand Gesture Snake
 *
 * Real per-session lesson content (no roadmap). 6 one-hour sessions for Class
 * 6. Each session ends with a runnable mini-snake plus a "Try this" tryout.
 *
 * Run with:   node backend/scripts/seedHandGestureSnakeProject.js
 */

const pool = require('../src/config/db');
const {
  createLearningTables,
  createLearningProject,
  replaceLearningContentChunks,
} = require('../src/models/learningModel');

const PROJECT_TITLE = 'Hand Gesture Snake';
const FALLBACK_CLASS_NAME = 'Class 6';
const SECTION_COUNT = 6;

const chunks = [
  {
    title: 'Before we start: what you need on the laptop',
    source_type: 'setup',
    audience: 'both',
    tags: ['setup', 'python', 'install'],
    content: [
      'Snake uses Python 3.11 or 3.12 (not 3.14). In Terminal:',
      '',
      '    cd hand_gesture_snake',
      '    python3.11 -m venv .venv',
      '    source .venv/bin/activate',
      '    pip install opencv-python mediapipe numpy',
      '',
      'Make a file called snake.py — every session adds to that same file. Run with python snake.py. Press Q to quit, R to restart later.',
      '',
      'NEW IDEA THIS PROJECT: instead of putting things at pixel positions (x = 543 pixels), Snake uses a GRID — say 32 columns by 18 rows of square cells. Every position is just (column, row). One cell = one snake segment. This makes the whole game cleaner.',
    ].join('\n'),
  },

  // S1
  {
    step_number: 1,
    title: 'Section 1: Today we draw a grid and put one dot on the cell your finger points to',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-1', 'grid', 'mediapipe'],
    content: [
      'TODAY: Draw a 32×18 grid of squares on a dark background. Find your index fingertip. Light up the ONE cell your finger is hovering over.',
      '',
      'WHY: In Snake, everything happens on a grid. So we need to convert "where my finger is in pixels" → "which cell that is". After that, every other rule is about cells, not pixels.',
      '',
      'TYPE THIS into snake.py:',
      '',
      '    import cv2, numpy as np, mediapipe as mp',
      '    CAMERA_WIDTH, CAMERA_HEIGHT = 1280, 720',
      '    GRID_COLS, GRID_ROWS = 32, 18',
      '    CELL = CAMERA_WIDTH // GRID_COLS   # 40 pixels per cell',
      '    TOP_BAR = CAMERA_HEIGHT - GRID_ROWS * CELL   # leftover row for HUD',
      '    mp_hands = mp.solutions.hands',
      '    camera = cv2.VideoCapture(0)',
      '    camera.set(cv2.CAP_PROP_FRAME_WIDTH, CAMERA_WIDTH)',
      '    camera.set(cv2.CAP_PROP_FRAME_HEIGHT, CAMERA_HEIGHT)',
      '    with mp_hands.Hands(max_num_hands=1) as hands:',
      '        while True:',
      '            ok, frame = camera.read()',
      '            if not ok: break',
      '            frame = cv2.flip(frame, 1)',
      '            display = np.zeros_like(frame); display[:] = (10, 12, 18)',
      '            # grid lines',
      '            for c in range(GRID_COLS+1):',
      '                cv2.line(display, (c*CELL, TOP_BAR), (c*CELL, CAMERA_HEIGHT), (40,44,60), 1)',
      '            for r in range(GRID_ROWS+1):',
      '                cv2.line(display, (0, TOP_BAR + r*CELL), (GRID_COLS*CELL, TOP_BAR + r*CELL), (40,44,60), 1)',
      '            # find finger and light up its cell',
      '            result = hands.process(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))',
      '            if result.multi_hand_landmarks:',
      '                lm = result.multi_hand_landmarks[0].landmark[8]',
      '                px, py = int(lm.x * CAMERA_WIDTH), int(lm.y * CAMERA_HEIGHT)',
      '                col = px // CELL',
      '                row = (py - TOP_BAR) // CELL',
      '                if 0 <= col < GRID_COLS and 0 <= row < GRID_ROWS:',
      '                    x = col * CELL; y = TOP_BAR + row * CELL',
      '                    cv2.rectangle(display, (x+3, y+3), (x+CELL-3, y+CELL-3), (255,255,0), -1)',
      '            cv2.imshow("Snake", display)',
      '            if cv2.waitKey(1) & 0xFF == ord("q"): break',
      '    camera.release(); cv2.destroyAllWindows()',
      '',
      'RUN IT. A dark grid appears. Move your finger — a single cyan cell lights up where you point.',
      '',
      'THE MATH: px // CELL is integer division. If px = 543 and CELL = 40, then 543 // 40 = 13. So pixel column 543 lands in grid column 13. That is how we go from camera pixels to grid cells in one line.',
      '',
      'TRY THIS: Change GRID_COLS to 16 (chunkier blocks). Then to 64 (tiny blocks). Then change the highlight colour to pink (190, 80, 255). Which size feels best for a snake game?',
    ].join('\n'),
  },

  // S2
  {
    step_number: 2,
    title: 'Section 2: Today a snake (3-cell list) crawls across the grid by itself',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-2', 'lists', 'auto-move'],
    content: [
      'TODAY: A snake is just a LIST of cells. snake[0] is the head. We make a 3-cell snake at the centre, and every fifth-of-a-second we move it one cell to the right.',
      '',
      'WHY: This is the heart of Snake. Auto-movement on a fixed beat. The list-based snake makes growth (next session) a one-line change.',
      '',
      'ADD at the top (after imports):',
      '',
      '    import time, random',
      '',
      'ABOVE the while loop, REPLACE everything between "with mp_hands.Hands..." and the while line with:',
      '',
      '    snake = [(GRID_COLS//2 - i, GRID_ROWS//2) for i in range(3)]',
      '    direction = (1, 0)   # moving right',
      '    last_tick = time.time()',
      '    TICK = 0.22          # seconds per move',
      '    with mp_hands.Hands(max_num_hands=1) as hands:',
      '',
      'REPLACE the finger-cell code inside the while loop with this auto-move + draw:',
      '',
      '            now = time.time()',
      '            if now - last_tick >= TICK:',
      '                head = snake[0]',
      '                new_head = (head[0] + direction[0], head[1] + direction[1])',
      '                snake.insert(0, new_head)',
      '                snake.pop()',
      '                last_tick = now',
      '            for i, (col, row) in enumerate(snake):',
      '                x = col * CELL; y = TOP_BAR + row * CELL',
      '                color = (255,255,0) if i == 0 else (200,200,0)',
      '                cv2.rectangle(display, (x+2, y+2), (x+CELL-2, y+CELL-2), color, -1)',
      '',
      'RUN IT. A 3-cell cyan snake crawls right and goes off the edge of the screen. We will fix that next session.',
      '',
      'WHY insert(0) THEN pop(): To move a snake by one cell, we add a new head and drop the tail. The whole body shifts forward by one — but we only changed two cells. Way cleaner than moving every body cell.',
      '',
      'TRY THIS: Change TICK to 0.5 (slow snake, easy game). Then 0.05 (zoom snake, impossible). Find the speed that feels fair. Then change direction = (1, 0) to direction = (0, 1) — the snake crawls DOWN. Try (-1, 0) — left. (0, -1) — up.',
    ].join('\n'),
  },

  // S3
  {
    step_number: 3,
    title: 'Section 3: Today the snake follows your hand direction',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-3', 'gesture-steering', 'state'],
    content: [
      'TODAY: We read your HAND POSITION on the camera. Hand on the left half → snake turns left. Right half → right. Top → up. Bottom → down. The snake KEEPS MOVING — you just steer.',
      '',
      'WHY: This is a different gesture style than Painter or Arcade. Those used absolute position. Snake uses DIRECTION. The hand tells the snake which way to go, then the snake moves on its own.',
      '',
      'ADD this helper function at the top of snake.py (after imports):',
      '',
      '    def desired_direction(hand_x, hand_y, current):',
      '        dx, dy = hand_x - 0.5, hand_y - 0.5',
      '        DEAD_ZONE = 0.12',
      '        if abs(dx) < DEAD_ZONE and abs(dy) < DEAD_ZONE:',
      '            return current  # hand near centre, keep going',
      '        if abs(dx) > abs(dy):',
      '            new = (1 if dx > 0 else -1, 0)',
      '        else:',
      '            new = (0, 1 if dy > 0 else -1)',
      '        if (new[0] + current[0], new[1] + current[1]) == (0, 0):',
      '            return current  # cannot reverse 180 degrees',
      '        return new',
      '',
      'INSIDE the while loop, AFTER you compute result, ADD:',
      '',
      '            if result.multi_hand_landmarks:',
      '                lms = result.multi_hand_landmarks[0].landmark',
      '                direction = desired_direction(lms[9].x, lms[9].y, direction)',
      '',
      'RUN IT. Tilt your hand left, right, up, down — the snake follows. Try to keep it on screen by steering away from the walls.',
      '',
      'THE DEAD ZONE: When your hand is near the middle (within 12% of centre), we DO NOT change direction. Without this, every tiny shake of the hand would flip the snake around and it would be impossible to play.',
      '',
      'THE 180° BLOCK: If the snake is moving RIGHT (1, 0) and we ask it to go LEFT (-1, 0), the sum is (0, 0). That means "directly opposite". We refuse the change because reversing means the new head lands inside the snake body — instant death. Try removing the if-check to see this happen!',
      '',
      'TRY THIS: Change DEAD_ZONE from 0.12 to 0.30 — much harder to turn (your hand has to swing wide). Then 0.05 — twitchy, turns too easily. Find a value that feels right.',
    ].join('\n'),
  },

  // S4
  {
    step_number: 4,
    title: 'Section 4: Today add FOOD — eat it, score points, grow longer',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-4', 'food', 'growth'],
    content: [
      'TODAY: A pink dot appears at a random cell. Drive your snake head into it. Score +10. Snake grows by one segment. A new food appears somewhere else.',
      '',
      'WHY: Without food, Snake is just a screensaver. The eat-and-grow loop is what makes the game addictive.',
      '',
      'ADD this helper near desired_direction:',
      '',
      '    def random_food(occupied):',
      '        free = [(x, y) for x in range(GRID_COLS) for y in range(GRID_ROWS) if (x, y) not in occupied]',
      '        return random.choice(free)',
      '',
      'ABOVE the while loop:',
      '',
      '    food = random_food(set(snake))',
      '    score = 0',
      '',
      'REPLACE your tick block with this version (snake grows when it eats):',
      '',
      '            if now - last_tick >= TICK:',
      '                head = snake[0]',
      '                new_head = (head[0] + direction[0], head[1] + direction[1])',
      '                snake.insert(0, new_head)',
      '                if new_head == food:',
      '                    score += 10',
      '                    food = random_food(set(snake))',
      '                else:',
      '                    snake.pop()   # only pop when NOT eating',
      '                last_tick = now',
      '',
      'INSIDE the while loop, ADD food drawing (before the snake-drawing loop):',
      '',
      '            fx, fy = food[0]*CELL, TOP_BAR + food[1]*CELL',
      '            cv2.circle(display, (fx+CELL//2, fy+CELL//2), CELL//2 - 4, (190,80,255), -1)',
      '            cv2.circle(display, (fx+CELL//2, fy+CELL//2), CELL//2 - 4, (245,245,245), 2)',
      '',
      'ADD a score in the HUD area (above the grid):',
      '',
      '            cv2.putText(display, f"SCORE {score}  LENGTH {len(snake)}", (24, 36),',
      '                        cv2.FONT_HERSHEY_SIMPLEX, 0.9, (245,245,245), 2)',
      '',
      'RUN IT. Steer your snake into the pink dot. SCORE 10. Snake gets one cell longer. New food appears. Steer again.',
      '',
      'WHY GROW = SKIP THE pop(): Normal movement is "add new head, drop tail" — body stays the same length. Eating is "add new head, KEEP the tail" — body gets one cell longer. That is literally the whole growth logic.',
      '',
      'TRY THIS: Change the food colour to yellow. Then change score += 10 to score += 25. Then make TWO foods exist at once — hint: keep a list called foods = [random_food(set(snake)), random_food(set(snake) | {food})] and loop over both for drawing and eating.',
    ].join('\n'),
  },

  // S5
  {
    step_number: 5,
    title: 'Section 5: Today GAME OVER — hit a wall or your own tail = you die',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-5', 'collision', 'game-over'],
    content: [
      'TODAY: Drive into a wall → game over. Drive into your own body → game over. A "GAME OVER" message appears and the snake stops. Press R to restart.',
      '',
      'WHY: Stakes! With game-over the kid actually CARES about steering well. Snake without death is just a list growing forever.',
      '',
      'ABOVE the while loop, ADD:',
      '',
      '    alive = True',
      '',
      'REPLACE your tick block with this safer version:',
      '',
      '            if alive and now - last_tick >= TICK:',
      '                head = snake[0]',
      '                new_head = (head[0] + direction[0], head[1] + direction[1])',
      '                # wall check',
      '                if not (0 <= new_head[0] < GRID_COLS and 0 <= new_head[1] < GRID_ROWS):',
      '                    alive = False',
      '                # self-collision check (compare against body EXCEPT the tail tip,',
      '                # because the tail moves away unless we ate this tick)',
      '                elif new_head in set(snake[:-1]):',
      '                    alive = False',
      '                else:',
      '                    snake.insert(0, new_head)',
      '                    if new_head == food:',
      '                        score += 10',
      '                        food = random_food(set(snake))',
      '                    else:',
      '                        snake.pop()',
      '                last_tick = now',
      '',
      'AFTER the snake-drawing loop, ADD a game-over overlay:',
      '',
      '            if not alive:',
      '                overlay = display.copy()',
      '                cv2.rectangle(overlay, (0,TOP_BAR), (CAMERA_WIDTH, CAMERA_HEIGHT), (0,0,0), -1)',
      '                cv2.addWeighted(overlay, 0.55, display, 0.45, 0, display)',
      '                cv2.putText(display, "GAME OVER", (CAMERA_WIDTH//2 - 220, CAMERA_HEIGHT//2),',
      '                            cv2.FONT_HERSHEY_SIMPLEX, 1.8, (190,80,255), 4)',
      '                cv2.putText(display, "press R to play again", (CAMERA_WIDTH//2 - 200, CAMERA_HEIGHT//2 + 50),',
      '                            cv2.FONT_HERSHEY_SIMPLEX, 0.8, (245,245,245), 2)',
      '',
      'ADD restart in the key handling:',
      '',
      '            key = cv2.waitKey(1) & 0xFF',
      '            if key == ord("q"): break',
      '            if key == ord("r"):',
      '                snake = [(GRID_COLS//2 - i, GRID_ROWS//2) for i in range(3)]',
      '                direction = (1, 0); food = random_food(set(snake))',
      '                score = 0; alive = True',
      '',
      'RUN IT. Try to crash into a wall — GAME OVER. Try to drive into your own body — GAME OVER. Press R, play again.',
      '',
      'WHY snake[:-1]: The tail tip is the LAST cell in the list. When the snake moves, that tail cell moves away in the same frame. So if our new head lands on the tail tip, it is NOT a real collision. snake[:-1] is "all of the snake EXCEPT the tail tip" — the cells that will still be there next frame.',
      '',
      'TRY THIS: Make the wall WRAP instead of kill — when the snake leaves the right edge, it reappears on the left. Hint: replace the wall check with new_head = (new_head[0] % GRID_COLS, new_head[1] % GRID_ROWS). Way easier game!',
    ].join('\n'),
  },

  // S6
  {
    step_number: 6,
    title: 'Section 6: Showcase — speed up over time, animated eyes, tournament!',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-6', 'polish', 'showcase'],
    content: [
      'TODAY: Three polish touches and then a class tournament. The snake speeds up every 4 foods (real challenge curve). Two little white eyes are drawn on the head so you can see where it is heading. Then everyone plays for the high score.',
      '',
      'WHY: A game without a challenge curve gets boring at score 50. Speeding up keeps it tense. The eyes are a tiny detail but they make the snake feel alive.',
      '',
      'ABOVE the while loop, ADD:',
      '',
      '    TICK_MIN = 0.08',
      '    SPEED_UP_EVERY = 4',
      '    foods_eaten = 0',
      '',
      'INSIDE the eat branch (where score += 10):',
      '',
      '                        foods_eaten += 1',
      '                        if foods_eaten % SPEED_UP_EVERY == 0:',
      '                            TICK = max(TICK_MIN, TICK - 0.018)',
      '',
      '(Note: change TICK from a constant to a regular variable above the loop so it can be reassigned.)',
      '',
      'AFTER the snake-drawing block, ADD eyes on the head:',
      '',
      '            head_col, head_row = snake[0]',
      '            cx = head_col * CELL + CELL//2',
      '            cy = TOP_BAR + head_row * CELL + CELL//2',
      '            dx, dy = direction',
      '            perp = (-dy, dx)',
      '            offset = CELL // 5',
      '            for sign in (1, -1):',
      '                ex = int(cx + dx*4 + perp[0]*offset*sign)',
      '                ey = int(cy + dy*4 + perp[1]*offset*sign)',
      '                cv2.circle(display, (ex, ey), 4, (245,245,245), -1)',
      '',
      'RUN IT. Eat 4 foods → snake gets faster. Eat 8 → faster again. Eyes look in the steering direction. Try to set a high score!',
      '',
      'WHY perp = (-dy, dx): That is the perpendicular direction. If the snake is moving RIGHT (1, 0), the perpendicular is (0, 1) — straight down. So the two eyes sit ONE above and ONE below the snake centre when moving right. Same trick works for any direction without writing four if-statements.',
      '',
      'TODAY\'S CLASSROOM TRY: TOURNAMENT! Every student gets 3 minutes of free practice, then ONE official run. Highest score wins. Longest snake wins separately. Most dramatic death also wins a prize. Three winners per class.',
      '',
      'TRYOUT FOR HOME: 1) Change the food to a BLUE colour but make it worth +50 (high-value rare food). Make one in 5 foods blue using random.random() < 0.2 when spawning. 2) BIG CHALLENGE: add a "pause" key (P) that freezes the game until you press P again. Hint: a boolean called paused, and skip the tick block when paused == True.',
    ].join('\n'),
  },
];

// ── Class resolver ───────────────────────────────────────────────────────────
const resolveTargetClass = async () => {
  const r = await pool.query(
    `SELECT class_name, grade FROM learning_projects WHERE class_name = $1 AND is_active = true LIMIT 1`,
    [FALLBACK_CLASS_NAME]
  );
  if (r.rows[0]) return { class_name: r.rows[0].class_name, grade: r.rows[0].grade || FALLBACK_CLASS_NAME };
  console.warn(`⚠️  No existing "${FALLBACK_CLASS_NAME}" project found — creating fresh.`);
  return { class_name: FALLBACK_CLASS_NAME, grade: FALLBACK_CLASS_NAME };
};

const seed = async () => {
  await createLearningTables();
  const { class_name, grade } = await resolveTargetClass();
  console.log(`📚 Assigning "${PROJECT_TITLE}" to class: ${class_name}`);
  const project = await createLearningProject({
    title: PROJECT_TITLE,
    subject: 'Computer Vision, Python, Game Programming',
    grade,
    class_name,
    description:
      'A 6-section project where students build the classic Snake game, but steered with hand direction instead of arrow keys. Each session adds one runnable piece — grid + finger cell, auto-moving snake, hand steering, food + growth, walls + self-collision + game over, polish + tournament.',
    learning_goals:
      'Convert pixel coordinates to grid coordinates, manage a Python list as a game entity (snake body), implement direction-based gesture control with a dead zone and 180-degree block, code growth as "skip the tail pop", build wall + self collision rules, design a restartable game loop with a difficulty curve.',
    difficulty_level: 'intermediate',
    duration_months: 1,
    expected_section_count: SECTION_COUNT,
    audience_scope: 'student_teacher',
    teacher_readiness_required: false,
    code_explanation_required: true,
    source_doc_name: 'hand_gesture_snake/snake.py',
    created_by_role: 'system',
  });
  const created = await replaceLearningContentChunks(project.id, chunks);
  return { project, class_name, chunk_count: created.length, sessions: SECTION_COUNT };
};

seed()
  .then((r) => { console.log('✅ Hand Gesture Snake learning project seeded'); console.log(JSON.stringify(r, null, 2)); })
  .catch((e) => { console.error('❌ Failed to seed Hand Gesture Snake project:', e.message); process.exitCode = 1; })
  .finally(async () => { await pool.end(); });
