/*
 * Seed: Hand Gesture DJ
 *
 * Real per-session lesson content (no roadmap). 7 one-hour sessions. Each
 * session ends with a runnable mini-program plus a "Try this" tryout.
 *
 * Run with:   node backend/scripts/seedHandGestureDjProject.js
 */

const pool = require('../src/config/db');
const {
  createLearningTables,
  createLearningProject,
  replaceLearningContentChunks,
} = require('../src/models/learningModel');

const PROJECT_TITLE = 'Hand Gesture DJ';
const FALLBACK_CLASS_NAME = 'JHS 2';
const SECTION_COUNT = 7;

const chunks = [
  {
    title: 'Before we start: what you need on the laptop',
    source_type: 'setup',
    audience: 'both',
    tags: ['setup', 'python', 'install', 'pygame'],
    content: [
      'For this DJ project you need Python 3.11 or 3.12 (not 3.14). In Terminal:',
      '',
      '    cd hand_gesture_dj',
      '    python3.11 -m venv .venv',
      '    source .venv/bin/activate',
      '    pip install opencv-python mediapipe numpy pygame',
      '',
      'pygame is new — we use it to play sound files. Make a folder called sounds/ inside hand_gesture_dj/ (we will fill it with WAV files our own code creates). Make a file gesture_dj.py. Run with python gesture_dj.py.',
    ].join('\n'),
  },

  // S1
  {
    step_number: 1,
    title: 'Section 1: Today the camera tracks your finger (starter)',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-1', 'mediapipe', 'cursor'],
    content: [
      'TODAY: Same cyan-dot starter as the other gesture projects. By the end of class your index finger drives a glowing dot on a dim background.',
      '',
      'WHY: The DJ pads will sit on screen. You will trigger them with the dot. So we need the dot working first — same recipe as before.',
      '',
      'TYPE THIS into gesture_dj.py:',
      '',
      '    import cv2, numpy as np, mediapipe as mp',
      '    mp_hands = mp.solutions.hands',
      '    camera = cv2.VideoCapture(0)',
      '    with mp_hands.Hands(max_num_hands=1) as hands:',
      '        while True:',
      '            ok, frame = camera.read()',
      '            if not ok: break',
      '            frame = cv2.flip(frame, 1)',
      '            display = cv2.addWeighted(frame, 0.25, np.zeros_like(frame), 0.75, 0)',
      '            result = hands.process(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))',
      '            if result.multi_hand_landmarks:',
      '                h, w = frame.shape[:2]',
      '                lm = result.multi_hand_landmarks[0].landmark[8]',
      '                pt = (int(lm.x * w), int(lm.y * h))',
      '                cv2.circle(display, pt, 22, (255, 255, 0), -1)',
      '            cv2.imshow("DJ", display)',
      '            if cv2.waitKey(1) & 0xFF == ord("q"): break',
      '    camera.release(); cv2.destroyAllWindows()',
      '',
      'RUN IT. Move your finger. Dot follows.',
      '',
      'TRY THIS: Change the cursor color when your hand is high on screen vs low on screen — for example, cyan above the middle, pink below. Hint: if pt[1] < display.shape[0]//2 then color = cyan else color = pink.',
    ].join('\n'),
  },

  // S2
  {
    step_number: 2,
    title: 'Section 2: Today we MAKE a drum sound from scratch with numpy',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-2', 'audio', 'numpy', 'wav'],
    content: [
      'TODAY: We synthesise a kick-drum sound using math, save it as a WAV file, and play it. No downloads — the code BUILDS the sound.',
      '',
      'WHY: Sound is just numbers in a list — 44,100 numbers for one second of audio (the sample rate). A kick is a low sine wave whose frequency drops and whose volume fades. We will write that recipe in 6 lines.',
      '',
      'CREATE a tiny test file called make_kick.py first (just to learn — separate from gesture_dj.py):',
      '',
      '    import numpy as np, wave',
      '    SAMPLE_RATE = 44100',
      '    duration = 0.42',
      '    t = np.linspace(0, duration, int(SAMPLE_RATE * duration), False)',
      '    frequency = 95 * np.exp(-t * 8) + 38   # frequency drops over time',
      '    phase = 2 * np.pi * np.cumsum(frequency) / SAMPLE_RATE',
      '    body  = np.sin(phase) * np.exp(-t * 9) # volume fades',
      '    samples = np.clip(body, -1, 1)',
      '    int16 = (samples * 32767).astype(np.int16)',
      '    with wave.open("sounds/kick.wav", "wb") as f:',
      '        f.setnchannels(1); f.setsampwidth(2); f.setframerate(SAMPLE_RATE)',
      '        f.writeframes(int16.tobytes())',
      '    print("wrote sounds/kick.wav")',
      '',
      'RUN python make_kick.py (make sure sounds/ folder exists). Open sounds/kick.wav with any music player — it should sound like a deep "boom".',
      '',
      'WHAT EACH LINE MEANS: np.linspace makes 44100*0.42 = ~18500 evenly spaced numbers from 0 to 0.42 seconds. frequency goes from 133 Hz down to 38 Hz over time (exp(-t*8) means "drops fast"). The sine wave at that frequency is the boom. The second exp(-t*9) makes the volume fade. *32767 converts 0–1 floats to int16 because WAV files store integers.',
      '',
      'TRY THIS: Change "95 * np.exp(-t * 8) + 38" to "200 * np.exp(-t * 4) + 80" — now it sounds like a tom, not a kick. Save it as sounds/tom.wav. You just made a second drum.',
    ].join('\n'),
  },

  // S3
  {
    step_number: 3,
    title: 'Section 3: Today we draw 4 pads on screen and touch them with the finger',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-3', 'pads', 'collision', 'pygame-sound'],
    content: [
      'TODAY: Draw 4 coloured rectangles (KICK, SNARE, CLAP, HAT). When your finger enters a rectangle, play that sound. Cooldown of 0.3 seconds so it does not retrigger 60 times a second.',
      '',
      'WHY: A pad is just a rectangle + a "is the finger inside?" check + a sound. Same pattern, four times.',
      '',
      'FIRST, copy your make_kick.py logic into a function ensure_sounds() inside gesture_dj.py that creates kick.wav, snare.wav, clap.wav, hat.wav if they do not exist. (Use the snare/clap/hat recipes from the original gesture_dj.py file in your project folder — make_snare(), make_clap(), make_hat() — same shape as make_kick.)',
      '',
      'ADD at top of gesture_dj.py:',
      '',
      '    import pygame, time',
      '    pygame.mixer.pre_init(44100, -16, 1, 256); pygame.mixer.init()',
      '    sounds = {n: pygame.mixer.Sound(f"sounds/{n}.wav") for n in ["kick","snare","clap","hat"]}',
      '',
      '    PADS = [   # (name, x1, y1, x2, y2, color)',
      '      ("KICK",   80, 120, 360, 280, (255,255,  0)),',
      '      ("SNARE", 400, 120, 680, 280, (190, 80,255)),',
      '      ("CLAP",  720, 120,1000, 280, (  0,245,255)),',
      '      ("HAT",  1040, 120,1280, 280, ( 90,255,100)),',
      '    ]',
      '    last_hit = {p[0]: 0.0 for p in PADS}',
      '',
      'INSIDE the loop, AFTER you compute pt, ADD:',
      '',
      '    for name, x1, y1, x2, y2, color in PADS:',
      '        hovered = result.multi_hand_landmarks and x1 <= pt[0] <= x2 and y1 <= pt[1] <= y2',
      '        cv2.rectangle(display, (x1, y1), (x2, y2), color, 4 if hovered else 2)',
      '        cv2.putText(display, name, (x1+30, (y1+y2)//2), cv2.FONT_HERSHEY_SIMPLEX, 1.4, (255,255,255), 3)',
      '        if hovered and time.time() - last_hit[name] > 0.3:',
      '            sounds[name.lower()].play()',
      '            last_hit[name] = time.time()',
      '',
      'RUN IT. Drag your finger across the four pads — each one BOOMS in its own colour.',
      '',
      'THE COOLDOWN: time.time() - last_hit[name] > 0.3 means "only play if the last trigger was over 0.3 seconds ago". Without it, hovering on one pad fires 60 times a second and sounds awful.',
      '',
      'TRY THIS: Rename HAT to BELL. Change CLAP\'s colour to orange. Then make the cooldown 0.15 (snappier, fits faster beats).',
    ].join('\n'),
  },

  // S4
  {
    step_number: 4,
    title: 'Section 4: Today we add 4 MORE pads — TOM, CRASH, LASER, CHIME',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-4', 'audio-design', 'sounds'],
    content: [
      'TODAY: From 4 pads to 8 pads in a 4-by-2 grid. Add new sound recipes (tom, crash, laser, chime). Each one teaches a different audio trick: long fade, noise, sweep, multi-tone.',
      '',
      'WHY: Variety = creativity. With 8 pads a student can actually make a beat. And each new sound recipe shows a fresh trick.',
      '',
      'ADD these recipes to ensure_sounds() (same pattern as make_kick from Session 2):',
      '',
      '    def make_crash():',
      '        t = np.linspace(0, 0.65, int(44100*0.65), False)',
      '        noise = np.random.uniform(-1, 1, len(t))',
      '        shimmer = np.sin(2*np.pi*6200*t) + np.sin(2*np.pi*9100*t)',
      '        return (noise*0.75 + shimmer*0.12) * np.exp(-t*4.5) * 0.55',
      '    def make_laser():',
      '        t = np.linspace(0, 0.36, int(44100*0.36), False)',
      '        freq = 760 * np.exp(-t*5.2) + 95   # sweep from high to low',
      '        phase = 2*np.pi*np.cumsum(freq)/44100',
      '        return np.sin(phase) * np.exp(-t*4) * 0.75',
      '    def make_chime():',
      '        t = np.linspace(0, 0.7, int(44100*0.7), False)',
      '        s = np.sin(2*np.pi*523*t) + np.sin(2*np.pi*659*t)*0.75 + np.sin(2*np.pi*784*t)*0.55',
      '        return s * np.exp(-t*3.5) * 0.38',
      '',
      'REWRITE the PADS list to be a 4×2 grid:',
      '',
      '    GRID = [["KICK","SNARE","CLAP","HAT"], ["TOM","CRASH","LASER","CHIME"]]',
      '    COLORS = {"KICK":(255,255,0), "SNARE":(190,80,255), "CLAP":(0,245,255), "HAT":(90,255,100),',
      '              "TOM":(0,170,255), "CRASH":(70,80,255), "LASER":(255,160,70), "CHIME":(255,90,200)}',
      '    PADS = []',
      '    pad_w, pad_h, gap, top = 280, 150, 24, 110',
      '    for row, names in enumerate(GRID):',
      '        for col, name in enumerate(names):',
      '            x1 = 54 + col*(pad_w + gap); y1 = top + row*(pad_h + gap)',
      '            PADS.append((name, x1, y1, x1+pad_w, y1+pad_h, COLORS[name]))',
      '    last_hit = {n: 0.0 for r in GRID for n in r}',
      '    sounds = {n.lower(): pygame.mixer.Sound(f"sounds/{n.lower()}.wav") for r in GRID for n in r}',
      '',
      'RUN IT. 8 pads. Try to play KICK, CLAP, KICK, CLAP — boom-clap, boom-clap. That is a 4-on-the-floor beat.',
      '',
      'WHY THE THREE TRICKS MATTER: make_crash uses pure NOISE (random numbers) — that is how cymbals sound. make_laser uses a FREQUENCY SWEEP — high to low — that is the "pew" of every sci-fi gun. make_chime adds THREE sine waves at musical notes C–E–G — that is a chord.',
      '',
      'TRY THIS: Write your own sound function. For example, make_meow() that sounds vaguely like a cat. Hint: start with two sweeping sine waves at 600 Hz and 800 Hz with different fades.',
    ].join('\n'),
  },

  // S5
  {
    step_number: 5,
    title: 'Section 5: Today add particle bursts when a pad fires',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-5', 'particles', 'visual-feedback'],
    content: [
      'TODAY: When a pad triggers, 30 coloured particles burst out from the centre, plus a growing ring. Same particle idea as Arcade Section 6.',
      '',
      'WHY: Without visual feedback the DJ feels mechanical. Particles make it FEEL like an instrument.',
      '',
      'ADD at top of file:',
      '',
      '    import math, random',
      '    from dataclasses import dataclass',
      '    @dataclass',
      '    class Particle:',
      '        x: float; y: float; vx: float; vy: float; life: float; color: tuple',
      '    @dataclass',
      '    class Ring:',
      '        x: float; y: float; r: float; life: float; color: tuple',
      '',
      'ABOVE the loop:',
      '',
      '    particles = []; rings = []',
      '    def burst(center, color, n=34):',
      '        for _ in range(n):',
      '            a = random.uniform(0, math.tau)',
      '            s = random.uniform(2, 11)',
      '            particles.append(Particle(center[0], center[1], math.cos(a)*s, math.sin(a)*s, 35, color))',
      '        rings.append(Ring(center[0], center[1], 8, 35, color))',
      '',
      'INSIDE the trigger branch (after sounds[...].play()), add:',
      '',
      '    cx, cy = (x1 + x2)//2, (y1 + y2)//2',
      '    burst((cx, cy), color)',
      '',
      'AFTER the PADS loop, ADD the particle update + draw:',
      '',
      '    alive_p = []',
      '    for p in particles:',
      '        p.x += p.vx; p.y += p.vy',
      '        p.vx *= 0.965; p.vy *= 0.965',
      '        p.life -= 1',
      '        if p.life > 0:',
      '            cv2.circle(display, (int(p.x), int(p.y)), 3, p.color, -1)',
      '            alive_p.append(p)',
      '    particles = alive_p[-500:]',
      '    alive_r = []',
      '    for r in rings:',
      '        r.r += 6; r.life -= 1',
      '        if r.life > 0:',
      '            cv2.circle(display, (int(r.x), int(r.y)), int(r.r), r.color, 3)',
      '            alive_r.append(r)',
      '    rings = alive_r',
      '',
      'RUN IT. Hit a pad → fireworks in that colour + a ring expanding outward. Now it FEELS like a real instrument.',
      '',
      'TRY THIS: Change the burst count from 34 to 80 — way more dramatic. Then change the ring speed from 6 to 20 — the ring zooms out.',
    ].join('\n'),
  },

  // S6
  {
    step_number: 6,
    title: 'Section 6: Today add gestures — pinch sparkles, open palm toggles dance lights',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-6', 'gestures', 'effects'],
    content: [
      'TODAY: Two new tricks. PINCH (thumb + index touching) plays a sparkle chime anywhere on screen. OPEN PALM toggles "dance lights" — coloured beams flashing across the whole screen.',
      '',
      'WHY: Pads are tap-to-play. Gestures are extra moves a real DJ would have. Same finger_up/distance ideas as Name Writer Session 4.',
      '',
      'ADD helpers at the top:',
      '',
      '    def distance(a, b): return math.hypot(a[0]-b[0], a[1]-b[1])',
      '    def finger_up(lms, tip, pip): return lms[tip].y < lms[pip].y - 0.015',
      '',
      'ABOVE the loop:',
      '',
      '    was_pinching = False; palm_was_open = False; dance_lights = True',
      '',
      'INSIDE the loop, in the multi_hand_landmarks branch, AFTER you compute pt, ADD:',
      '',
      '    lms = result.multi_hand_landmarks[0].landmark',
      '    thumb_pt = (int(lms[4].x*w), int(lms[4].y*h))',
      '    pinching = distance(pt, thumb_pt) < 44',
      '    palm_open = (finger_up(lms,8,6) and finger_up(lms,12,10) and finger_up(lms,16,14) and finger_up(lms,20,18))',
      '    if pinching and not was_pinching:',
      '        sounds["chime"].play(); burst(pt, (190,80,255), 60)',
      '    if palm_open and not palm_was_open:',
      '        dance_lights = not dance_lights',
      '    was_pinching = pinching; palm_was_open = palm_open',
      '',
      'ADD dance lights drawing (before the PADS loop):',
      '',
      '    if dance_lights:',
      '        overlay = display.copy()',
      '        for i in range(8):',
      '            cx = int((i + 0.5) * display.shape[1] / 8)',
      '            color = [(0,245,255),(190,80,255),(0,255,255),(90,255,100),(255,90,200),(255,160,70)][i % 6]',
      '            beam = int(80 + 28*math.sin(time.time()*2 + i))',
      '            pts = np.array([(cx-18,0),(cx+18,0),(cx+beam,display.shape[0]),(cx-beam,display.shape[0])], np.int32)',
      '            cv2.fillPoly(overlay, [pts], color)',
      '        cv2.addWeighted(overlay, 0.08, display, 0.92, 0, display)',
      '',
      'RUN IT. Pinch in midair → SPARKLE + sound. Open palm → dance lights flicker on/off.',
      '',
      'THE "EDGE TRIGGER" TRICK: pinching and not was_pinching only fires ONCE — the exact frame the pinch starts. Without it, holding the pinch would fire chime 60 times a second.',
      '',
      'TRY THIS: Change the dance light colors to all green (jungle vibe). Then change the alpha 0.08 to 0.25 — much more intense, almost a strobe.',
    ].join('\n'),
  },

  // S7
  {
    step_number: 7,
    title: 'Section 7: Showcase — score, combo, HUD, reset, perform!',
    source_type: 'lesson',
    audience: 'both',
    tags: ['session-7', 'polish', 'showcase'],
    content: [
      'TODAY: Add a SCORE (every pad = +5), a COMBO counter (hitting DIFFERENT pads in a row builds combo), a HUD bar at the top, and an R key to reset. Then PERFORM.',
      '',
      'WHY: Scoring rewards rhythm. Combo rewards variety (no spamming one pad). HUD + reset = it feels like a real DJ app.',
      '',
      'ABOVE the loop:',
      '',
      '    score = 0; combo = 0; last_pad = ""',
      '',
      'INSIDE the trigger branch (right after sounds[...].play()):',
      '',
      '    if name != last_pad:',
      '        combo += 1',
      '    score += 5 + min(combo*2, 30)',
      '    last_pad = name',
      '',
      'AFTER the pad loop, ADD a HUD bar at the top:',
      '',
      '    cv2.rectangle(display, (0,0), (display.shape[1], 88), (12,12,18), -1)',
      '    cv2.putText(display, "HAND GESTURE DJ", (28, 38), cv2.FONT_HERSHEY_SIMPLEX, 1.0, (255,255,255), 2)',
      '    cv2.putText(display, f"SCORE {score}", (380, 38), cv2.FONT_HERSHEY_SIMPLEX, 0.82, (0,245,255), 2)',
      '    cv2.putText(display, f"COMBO x{combo}", (570, 38), cv2.FONT_HERSHEY_SIMPLEX, 0.82, (255,255,0), 2)',
      '    cv2.putText(display, f"LIGHTS {\'ON\' if dance_lights else \'OFF\'}", (780, 38), cv2.FONT_HERSHEY_SIMPLEX, 0.82, (90,255,100), 2)',
      '',
      'INSIDE the key handling, ADD:',
      '',
      '    if key == ord("r"):',
      '        score = 0; combo = 0; last_pad = ""',
      '        particles.clear(); rings.clear()',
      '',
      'RUN IT. Try to play a beat: KICK SNARE KICK SNARE — combo goes up each time you switch pads.',
      '',
      'TODAY\'S CLASSROOM TRY: Every student gets 30 seconds to perform a beat in front of the class. Highest score wins, biggest combo wins, most creative beat wins.',
      '',
      'TRYOUT FOR HOME: 1) Add a NINTH pad called "SILENCE" that, instead of playing a sound, mutes the next pad for 1 second (good for dramatic pauses). 2) Use the gesture pinch to TRIPLE-tap the most recent pad — turning any beat into a drum roll.',
    ].join('\n'),
  },
];

const resolveTargetClass = async () => {
  const r = await pool.query(
    `SELECT class_name, grade FROM learning_projects WHERE class_name = $1 AND is_active = true LIMIT 1`,
    [FALLBACK_CLASS_NAME]
  );
  if (r.rows[0]) return { class_name: r.rows[0].class_name, grade: r.rows[0].grade || FALLBACK_CLASS_NAME };
  console.warn(`⚠️  No existing "${FALLBACK_CLASS_NAME}" project found — creating fresh.`);
  return { class_name: FALLBACK_CLASS_NAME, grade: FALLBACK_CLASS_NAME };
};

const seed = async () => {
  await createLearningTables();
  const { class_name, grade } = await resolveTargetClass();
  console.log(`📚 Assigning "${PROJECT_TITLE}" to class: ${class_name}`);
  const project = await createLearningProject({
    title: PROJECT_TITLE,
    subject: 'Computer Vision, Python, Audio Synthesis',
    grade,
    class_name,
    description:
      'A 7-section project where students synthesise drum sounds from math, draw on-screen pads, and play them with a fingertip cursor. Each session adds one runnable piece — cursor, sound synthesis, pads, more sounds, particle effects, pinch + palm gestures, scoring + showcase. Last session is a class beat-performance battle.',
    learning_goals:
      'Generate audio samples with numpy (sine, noise, frequency sweeps, additive chords), write WAV files, load and play sounds with pygame.mixer, detect when a finger enters a rectangle, manage cooldowns and edge-triggered gestures (pinch, open palm), and build particle + ring visual feedback for actions.',
    difficulty_level: 'intermediate',
    duration_months: 2,
    expected_section_count: SECTION_COUNT,
    audience_scope: 'student_teacher',
    teacher_readiness_required: false,
    code_explanation_required: true,
    source_doc_name: 'hand_gesture_dj/gesture_dj.py',
    created_by_role: 'system',
  });
  const created = await replaceLearningContentChunks(project.id, chunks);
  return { project, class_name, chunk_count: created.length, sessions: SECTION_COUNT };
};

seed()
  .then((r) => { console.log('✅ Hand Gesture DJ learning project seeded'); console.log(JSON.stringify(r, null, 2)); })
  .catch((e) => { console.error('❌ Failed to seed Hand Gesture DJ project:', e.message); process.exitCode = 1; })
  .finally(async () => { await pool.end(); });
